### ISSUE TITLE
Missing alarm function description in SDK documentation

### ISSUE THREAD

**Issue by Volksolive** [raspberrypi/pico-sdk#164] opened 2021-02-19 14:39 UTC
The function hardware_alarm_set_target is referenced is the 4.1.22.3.5. hardware_alarm_set_callback function but its description is missing, also not listed in 4.1.22.2. Function List.

**Comment by lurch** [comment] 2021-02-19 14:48
Duplicate of #131 which is already fixed by #147 :slightly_smiling_face:

**Comment by aallan** [comment] 2021-02-19 14:51
That's the sort of issue we like, one we've already fixed. Will be in the next SDK release.

**Closed by aallan** 2021-02-19 14:51 UTC

**Comment by Volksolive** [comment] 2021-02-19 16:13
Sorry, I only checked the open issue ...
