### ISSUE TITLE
hardware_gpio depends on hardware_irq but hardware_gpio_headers does not depend on hardware_irq_headers

### ISSUE THREAD

**Issue by ooxi** [raspberrypi/pico-sdk#955] opened 2022-08-03 18:30 UTC
When trying to `#include <hardware/gpio.h>` while depending on `hardware_gpio_headers`, I get a compile error

```
pico-sdk/src/rp2_common/hardware_gpio/include/hardware/gpio.h:14:10: fatal error: hardware/irq.h: No such file or directory
   14 | #include "hardware/irq.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

This is caused by `hardware_gpio_headers` not depending on `hardware_irq_headers`. This is not an issue for `hardware_gpio` since it depends on `hardware_irq` (see [hardware_gpio/CMakeLists.txt](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_gpio/CMakeLists.txt#L2)):

```
pico_simple_hardware_target(gpio)
target_link_libraries(hardware_gpio INTERFACE hardware_irq)
```

**Comment by kilograham** [comment] 2022-08-04 00:27
duplicate of #882

**Closed by kilograham** 2022-08-04 00:27 UTC
