### ISSUE TITLE
Pico W SDK CYW43 Driver calls "pio_sm_set_enabled" with hard-coded number instead of bus_data_t->pio_sm value

### ISSUE THREAD

**Issue by dlkeng** [raspberrypi/pico-sdk#1185] opened 2023-01-22 00:57 UTC
In file: **pico-sdk/src/rp2_common/cyw43_driver/cyw43_bus_pio_spi.c**
Function: **cyw43_spi_transfer()**
Line: **307**
Function *pio_sm_set_enabled()* is called with hard-coded value of 0 for the PIO state machine number.
       `  pio_sm_set_enabled(bus_data->pio, 0, true);`
-Probably should be-
        `  pio_sm_set_enabled(bus_data->pio, bus_data->pio_sm, true);`
This could be a problem if another PIO program was installed on state machine 0 before the CYW43 driver was initialized.

**Comment by lurch** [comment] 2023-01-22 15:22
Already fixed by #1080 ?

**Comment by kilograham** [comment] 2023-01-22 16:05
duplicate of #1077

**Closed by kilograham** 2023-01-22 16:05 UTC
