### ISSUE TITLE
pico_time_headers must not depend on hardware_timer

### ISSUE THREAD

**Issue by ooxi** [raspberrypi/pico-sdk#1154] opened 2022-12-23 20:32 UTC
The [`pico_time_headers`](https://github.com/raspberrypi/pico-sdk/blob/master/src/common/pico_time/CMakeLists.txt#L6) target currently depends on `hardware_timer` instead of `hardware_timer_headers`, pulling in implementation when only headers are required.

**Comment by kilograham** [comment] 2022-12-23 20:45
duplicate of #1138

**Closed by kilograham** 2022-12-23 20:45 UTC
