### ISSUE TITLE
SWD failures seemingly related to openocd utility

### ISSUE THREAD

**Issue by seamusdemora** [raspberrypi/pico-sdk#1611] opened 2024-01-22 20:02 UTC
On a RPi 5 running bookworm Lite; "fairly close" to pristine.

I have installed iaw the instructions; i.e. ran  `./pico_setup.sh`
I have wired up the SWD iaw the documentation; i.e.
```
I've triple-checked the wiring, and it is IAW the Guide:
SWDIO (Pico) ===> connected to ===> GPIO 24 (RPi pin 18)
SWCLK (Pico) ===> connected to ===> GPIO 25 (RPi pin 22)
  GND (Pico) ===> connected to ===> GND (RPi pin 20)
```

Unfortunately, it does not work: 
```
$ openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program blink/blink.elf verify reset exit"
Open On-Chip Debugger 0.12.0-g4d87f6d (2024-01-20-06:51)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
WARNING: Unknown type of the host SoC. Expect JTAG/SWD clock slower than requested.
Warn : TMS/SWDIO moved to GPIO 8 (pin 24). Check the wiring please!
adapter speed: 5000 kHz

Info : Hardware thread awareness created
Info : Hardware thread awareness created
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Error: open: Permission denied
** OpenOCD init failed **
shutdown command invoked
```

I emphasize again that the wiring is done IAW the documentation. So given that the error message (or the documentation) is incorrect, what must be done to get this working?

**Comment by aallan** [comment] 2024-01-22 20:39
Can you point me at the documentation (website, or PDF) you are following?

**Comment by seamusdemora** [comment] 2024-01-22 22:38
Surely, it's the [Getting Started Guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf).

**Comment by aallan** [comment] 2024-01-22 22:44
These instructions need updating for Raspberry Pi 5. See raspberrypi/openocd#93 the PR linked from there raspberrypi/pico-setup#28. Now folks are back from the holidays it's likely we'll see some movement there.

**Comment by aallan** [comment] 2024-01-22 22:45
@nathan-contino Can you take a look at raspberrypi/openocd#93 and see if we can squeeze this into the upcoming documentation release? Willing to punt for a couple of days if you think it's doable. Thanks!

**Comment by seamusdemora** [comment] 2024-01-22 22:56
@aallan :  

Thanks for the rapid update!  

After reading [raspberrypi/openocd#93](https://github.com/raspberrypi/openocd/issues/93) I am still a little unclear on the fix... is a change to the config file all that's required, or is there some code in linuxgpiod.c that must also be updated?

**Comment by cleverca22** [comment] 2024-01-23 07:42
@seamusdemora just create the `test.cfg` file and use it as shown in the comments
shouldnt be any need to change source in `linuxgpiod.c`

**Comment by seamusdemora** [comment] 2024-01-23 08:43
@cleverca22 : 

Do you mean this file?: 

```
clever@raspberrypi:~ $ cat test.cfg
adapter driver linuxgpiod
adapter gpio swclk 20 -chip 4
adapter gpio swdio 21 -chip 4
``` 

And apologies, but I'm not following your **context**...  I mean where does this test.cfg file go? It looks like you're running `openocd` from your `~/` directory, but where's `target`? 

P.S. I am not at all familiar with `openocd`.

**Comment by aallan** [comment] 2024-01-26 11:06
Fixed in the next documentation update, which should be out within the next few days.

**Closed by aallan** 2024-01-26 11:06 UTC

**Comment by cleverca22** [comment] 2024-02-02 10:00
@seamusdemora 
> but where's `target`?

any time openocd cant find a file you gave it, then it will search its built in scripts
which are somewhere under /usr/local if you built from source

https://github.com/raspberrypi/openocd/tree/rp2040-v0.12.0/tcl/target
this is the source that those built-in scripts come from

**Comment by hasenradball** [comment] 2024-02-11 14:34
@aallan 
Hi Sir, my I ask a question?
Is it meaning when the topic is closed now does it mean, that the Pico C SDK runs fine on the pi 5 now?
Or there are still open issues?

Best regards
Frank

**Comment by hasenradball** [comment] 2024-02-15 18:22
@nathan-contino 
I checked the new documentation, but I don't get it to work.

Are the SWDIO and SWCLK Ports changed in Pi5?

I created a file like in the description mentioned and it look like this:

![20240215_19h18m31s_grim](https://github.com/raspberrypi/pico-sdk/assets/26808969/e44e40b0-6336-40ac-9310-93997cba609f)

And the error meassage looks like this:
![20240215_19h17m52s_grim](https://github.com/raspberrypi/pico-sdk/assets/26808969/47840304-983d-461e-b7f7-3a72b2dc2478)

What do I wrong???

**Comment by hasenradball** [comment] 2024-02-15 18:35
@nathan-contino
If I set the cfg to this:

```
source [find interface/raspberrypi-native.cfg]

adapter driver linuxgpiod

adapter gpio swclk 20 -chip 4
adapter gpio swdio 21 -chip 4

adapter speed 5000
```


I get this error:
![20240215_19h30m24s_grim](https://github.com/raspberrypi/pico-sdk/assets/26808969/fb7073bf-d593-4903-9496-1602ae46e519)

**Comment by nathan-contino** [comment] 2024-02-15 18:42
@hasenradball sorry about that. It looks like we have more investigating to do.

Can you try compiling with the options in https://github.com/raspberrypi/pico-setup/pull/28 ? That's the only reason I can think of that this would fail with the current setup. Otherwise I'll have to do more digging and reproduce the issue.

**Comment by hasenradball** [comment] 2024-02-15 19:28
@nathan-contino 
Can you please give me the options I should use, Thanks

**Comment by nathan-contino** [comment] 2024-02-15 19:47
You should be able to copy and paste the contents of [`pico_setup.sh`](https://github.com/lurk101/pico-setup/blob/master/pico_setup.sh) from the fork used in that PR into a bash file on your own system, then run it locally to install OpenOCD with pi 5-friendly GPIO libraries.

**Comment by hasenradball** [comment] 2024-02-15 19:48
@nathan-contino
If you mean this???

This PR is still open!

![grafik](https://github.com/raspberrypi/pico-sdk/assets/26808969/2817d1ae-f350-4b61-8c9f-5e0e9ca63ea9)

**Comment by hasenradball** [comment] 2024-02-15 20:09
@nathan-contino 
Running the `pico_setup.sh` with the above mentioned options, does not help.

Can ypu please paste how the cfg-file for th Pi5 should look like?

Thank you.

**Comment by hasenradball** [comment] 2024-02-15 20:42
> You should be able to copy and paste the contents of [`pico_setup.sh`](https://github.com/lurk101/pico-setup/blob/master/pico_setup.sh) from the fork used in that PR into a bash file on your own system, then run it locally to install OpenOCD with pi 5-friendly GPIO libraries.
> 
> It seems that the version of openocd you're using wasn't built with those libraries, hence your issue.
> 
> I tested on Linux and macOS, but I don't have a Windows box to test on and I can't cover all possible environments anyway.

I tested it on the Pi5 with rasparian bookworm.
No changes in the error message.

Can you give a screenshot of your pi5 cfg file for openocd?

**Comment by nathan-contino** [comment] 2024-02-15 20:45
Thank you for your feedback. I'll investigate this when I get some spare cycles to try to reproduce the issue.

**Comment by hasenradball** [comment] 2024-02-15 21:19
> Thank you for your feedback. I'll investigate this when I get some spare cycles to try to reproduce the issue.

Can you please paste the content of your config!!!
To be able to check how it should look like.

**Comment by ivt18** [comment] 2024-02-15 22:09
Good evening, I am currently facing similar issues with this. After building OpenOCD from source, and with `libgpio-dev`, I now get the following output:
```
$ openocd -f raspberrypi5-swd.cfg -f target/rp2040.cfg -c "program build/src/main.elf verify reset exit"
Open On-Chip Debugger 0.12.0-g4d87f6d (2024-02-15-22:50)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : Hardware thread awareness created
Info : Hardware thread awareness created
Warn : An adapter speed is not selected in the init scripts. OpenOCD will try to run the adapter at the low speed (100 kHz)
Warn : To remove this warnings and achieve reasonable communication speed with the target, set "adapter speed" or "jtag_rclk" in the init scripts.
Info : Linux GPIOD JTAG/SWD bitbang driver
Info : This adapter doesn't support configurable speed
Error: Failed to connect multidrop rp2040.dap0
in procedure 'program'
** OpenOCD init failed **
shutdown command invoked
```
I have connected the RPi 5 SWD according to the [Getting Started Guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf), and I'm using the following config:
```
$ cat raspberrypi5-swd.cfg 
adapter driver linuxgpiod
adapter gpio swclk 20 -chip 4
adapter gpio swdio 21 -chip 4
```
Am I doing something wrong?

**Comment by hasenradball** [comment] 2024-02-15 22:10
@nathan-contino @aallan @lurch 
What the hell was done in the review before the Documentation update release???

Hi I don' t belive what I see here....
Have you read the last sentence in this screenshot?

![grafik](https://github.com/raspberrypi/pico-sdk/assets/26808969/c9c7c095-eac9-47c2-adc6-2e6e5419fe20)

Somebody changed the PINs for `SWDIO` and `SWCLK`, because it was for him a better place to use these pins but this does nothing have to do with the `Getting startetd Guide`
And some stupid guy takes this over into an official Documentation release???

If I completly rebuild openocd like this approach:
![grafik](https://github.com/raspberrypi/pico-sdk/assets/26808969/4547d408-f913-43f0-add6-74c57551494b)

 


The working config file for the official Pi Documentation should look like this:

```
adapter driver linuxgpiod
adapter gpio swclk 25 -chip 4
adapter gpio swdio 24 -chip 4
```
And PLEASE !!!!

1) Can anyone merge this PR immediately into the master [PR28](https://github.com/raspberrypi/pico-setup/pull/28)
AND 
2) The guy how has tomatos on the eyes please correct to official release for this in chapter 5:
[Getting Started Guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf)

![grafik](https://github.com/raspberrypi/pico-sdk/assets/26808969/5040ed0e-07ee-4e0f-95ae-b0263d5225bb)

**Comment by ivt18** [comment] 2024-02-15 22:13
@hasenradball Welp, that fixed it. I must say I was skeptical at the 21/20 pins indicated on the documentation, but trusted it would be correct. I stand corrected.

**Comment by nathan-contino** [comment] 2024-02-15 22:20
Thanks for all of the feedback here. I've updated the source code and we'll roll out the fix in the next release. Sorry that the config file pin assignment was wrong in that last release.

Please try and be polite; mistakes do happen in documentation. Fortunately I have successfully removed the tomatoes from my eyes so this one shouldn't happen again.

**Comment by hasenradball** [comment] 2024-02-15 22:20
Thanks for your feedback.
I was also suspicious but, I believed an actual official release of documentation more then my doupt.

**Comment by hasenradball** [comment] 2024-02-15 22:21
> Thanks for all of the feedback here. I've updated the source code and we'll roll out the fix in the next release. Sorry that the config file pin assignment was wrong in that last release.
> 
> Please try and be polite; mistakes do happen in documentation. Fortunately I have successfully removed the tomatoes from my eyes so this one shouldn't happen again.

@nathan-contino 
Sorry I was so so angry...

**Comment by hasenradball** [comment] 2024-02-15 22:33
@nathan-contino 
If you are interested in, I can give you an example to setup a task in vscode to flash the code on the pico via key short cut.

**Comment by hasenradball** [comment] 2024-02-16 06:39
@nathan-contino Hi just for clarifikation,
you also have to take over the changes from the PR28 (the changes in the pico_setup.sh.

I would recommend to take over this PR immediately, because rebuild of openocd is not so easy than using the setup script.
And running the setup script twice after changed the parameters won‘ t help here.

**Comment by lurk101** [comment] 2024-02-18 20:09
I'm afraid PR#28 is now closed. I had to delete the originating repo. I figured over a month with no merge was long enough to be ignored!

**Comment by hasenradball** [comment] 2024-02-18 20:21
> I'm afraid PR#28 is now closed. I had to delete the originating repo. I figured over a month with no merge was long enough to be ignored!

Welp, that seems to be a main problem I faced a similar problem.
:-(

**Comment by hasenradball** [comment] 2024-02-18 20:25
@nathan-contino 
One Question, you mentioned you took over the changes.
Did you took over both parts?
a) the change in the pico_ setup.sh
and
b) the change in the docu?

a) could be take over immidiately, from my undastaning.

**Comment by lurk101** [comment] 2024-02-18 22:14
> > I'm afraid PR#28 is now closed. I had to delete the originating repo. I figured over a month with no merge was long enough to be ignored!
> 
> Welp, that seems to be a main problem I faced a similar problem. :-(

I think you can still use it. Just select closed PRs instead of open ones, then you can look at the commit.

**Comment by lurk101** [comment] 2024-02-18 22:15
> > I'm afraid PR#28 is now closed. I had to delete the originating repo. I figured over a month with no merge was long enough to be ignored!
> 
> Welp, that seems to be a main problem I faced a similar problem. :-(

I think you can still use it. Just select closed PRs instead of open ones, then you can look at the commit.

**Comment by hasenradball** [comment] 2024-02-20 07:11
> > > I'm afraid PR#28 is now closed. I had to delete the originating repo. I figured over a month with no merge was long enough to be ignored!
> > 
> > 
> > Welp, that seems to be a main problem I faced a similar problem. :-(
> 
> I think you can still use it. Just select closed PRs instead of open ones, then you can look at the commit.

Could you please reopen it?

**Comment by lurk101** [comment] 2024-02-20 13:05
Not possible. The originating repo has been deleted.
