### ISSUE TITLE
stdio_init_all() very slow in sdk 2.0

### ISSUE THREAD

**Issue by liubinbj** [raspberrypi/pico-sdk#1902] opened 2024-09-04 11:23 UTC
in the old sdk 1.x , that function runs very fast, but in sdk 2.0 , it takes about 3s, it's funny. I guess it is a problem!

**Comment by peterharperuk** [comment] 2024-09-04 11:59
Is this to connect to usb or uart? Are you running one of the pico-examples?

**Comment by liubinbj** [comment] 2024-09-04 12:08
> Is this to connect to usb or uart? Are you running one of the pico-examples?

it connect to usb.  not examples, but one of my projects.

pico_enable_stdio_usb(skydogge 1)
pico_enable_stdio_uart(skydogge 0)


the stdio_init_all() is first line in the main(), but it takes 3 seconds, if use sdk 1.x , it's very fast.

**Comment by liubinbj** [comment] 2024-09-04 12:55
> PICO_STDIO_USB_CONNECT_WAIT_TIMEOUT_MS

don't know that and not set that value, and then I set  PICO_STDIO_USB_CONNECT_WAIT_TIMEOUT_MS=0 to test. still have 3s delay, with or without usb connection.

**Comment by arturo182** [comment] 2024-09-04 17:02
Probably best way to analyze would be to connect a debugger and stop execution during those 3s to see what the MCU doin.

**Comment by peterharperuk** [comment] 2024-09-23 14:22
Cannot reproduce. for me it takes about 0.5 ms. You'll have to attach an example that demonstrates the issue. The only reason it would take seconds is if it's waiting for usb to connect.

**Comment by kilograham** [comment] 2024-11-11 17:55
closing as not reproducable

**Closed by kilograham** 2024-11-11 17:55 UTC
