### ISSUE TITLE
PIO gpiobase not set with pin >= 32

### ISSUE THREAD

**Issue by sfe-SparkFro** [raspberrypi/pico-sdk#2030] opened 2024-11-08 18:36 UTC
I tried running the [PIO WS2812 example](https://github.com/raspberrypi/pico-examples/blob/master/pio/ws2812/ws2812.c) with an RP2350B, and found that the LED does not work when using a GPIO pin >=32. After some digging, it appears the root problem is that the `pio->gpiobase` is not getting set to `16`. If I manually set the value, it works fine with GPIO pins >= 32.

Where is the correct place for `gpiobase` to be set? I put the following check into [`pio_sm_set_consecutive_pindirs()`](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/hardware_pio/pio.c#L270) which worked for me, but I'm guessing it may be better to go somewhere else.

```
if(pin > 31 && pio_get_gpio_base(pio) == 0)
    pio->gpiobase = 0x10;
```

**Comment by sfe-SparkFro** [comment] 2024-11-08 18:37
Also, not sure whether #1834 is related

**Comment by lurch** [comment] 2024-11-11 11:05
I wonder if this ought to be classed as a bug in the PIO WS2812 example? Perhaps there needs to be a call to `pio_set_gpio_base()` in https://github.com/raspberrypi/pico-examples/blob/develop/pio/ws2812/ws2812.pio#L36 ? :shrug: 
Disclaimer: I've not written any PIO code myself :joy:

**Comment by sfe-SparkFro** [comment] 2024-11-13 17:08
I did consider whether it should be an issue with the example, but decided against that because IMO the SDK should abstract away things like setting `gpiobase`. The user should only have to worry about which PIO and pin they're using, which is why I opened the issue here. Although I've not written much PIO code either, so I'm not sure if this is something the user should actually need to worry about, but my naïve feeling is that the user shouldn't have to do things differently for GPIO >=32.

**Comment by lurch** [comment] 2024-11-13 17:17
From what little I understand, I'm not sure how much the SDK can do "automatically" because you're **never** going to have PIO code which simultaneously works with pins 10 and 40? (because one is in the 0-32 range and the other is in the 16-48 range)

**Comment by StijnKuipers** [comment] 2024-11-14 15:46
also - it is unclear how other pio related functions behave after a base is set. 

 pio_set_gpio_base(pio, 16);
 pio_gpio_init(pio, somepin);    <-- does somepin now need to be offset by 16? or is gpio number absolute? 
 sm_config_set_out_pins(&sm, somepin, 1); <-- how about here? 

 same for all other pio and sm functions that expect a pin number

**Comment by shtirlic** [comment] 2024-11-14 15:52
Here some info about the sm functions, also there is some magic with pioasm detection what range of pins is used, affecting fail to set gpio base

**Comment by shtirlic** [comment] 2024-11-14 15:58
> From what little I understand, I'm not sure how much the SDK can do "automatically" because you're **never** going to have PIO code which simultaneously works with pins 10 and 40? (because one is in the 0-32 range and the other is in the 16-48 range)
 Theoretically it can be done if you can merge 2 PIO blocks , for Example PIO1+PIO2 and  we get a virtual PIO3 with all 48 pins and base 0

**Comment by peterharperuk** [comment] 2024-11-14 16:51
@StijnKuipers I believe both the functions you mention there handle things properly, i.e. you can pass a gpio number >31 and they should do the right thing.

**Comment by Octopus1633** [comment] 2024-11-19 10:38
@StijnKuipers @sfe-SparkFro 
Hello, I would like to ask how you solved this problem.I am testing the [hello_pio](https://github.com/raspberrypi/pico-examples/tree/master/pio/hello_pio) program. And I also use the RP2350B. I want to use pin 45 to output high and low levels alternately.

I tried adding

```C
pio_set_gpio_base(pio,16);
```
and changing the pin to 45

```C
#define HELLO_PIO_LED_PIN 45
```
and found that the pin did not respond.

Then I tried to change the pin to a relative value

```C
#define HELLO_PIO_LED_PIN (45-16)
```
Still no response, why is this?

**Comment by sfe-SparkFro** [comment] 2024-11-19 16:47
@Octopus1633 See my first message in this thread. That solution worked for my specific situation with the WS2812 PIO example, but I'm not sure whether that will work for every situation. I don't know enough about the PIO API to know what the "right" solution would be.

This issue has been assigned to the [v2.1.0 milestone](https://github.com/raspberrypi/pico-sdk/milestone/22), so I'm guessing it will be addressed soon, but they're probably finishing work on other things right now.

**Comment by peterharperuk** [comment] 2024-11-20 18:16
Closing this as I'm fairly happy there's nothing else to fix here. Please reopen if you disagree. The simple answer is to use pio_claim_free_sm_and_add_program_for_gpio_range.

**Closed by peterharperuk** 2024-11-20 18:16 UTC

**Comment by poetaster** [comment] 2026-02-12 18:20
I feel uncomfortable opening this up again, but I'm unable to get pio in both ranges working at the same time. I'm attempted to explicitly set the PIO pio0 / pio1 and 'trust' in pio_claim_free_sm_and_add_program_for_gpio_range but I can only use one or the other range. Is this intended?

I have (arduino) objects that instantiate like:
```
void PioEncoder::begin(){
    pinMode(pin, INPUT);
    pinMode(pin+1, INPUT);

    bool success = pio_claim_free_sm_and_add_program_for_gpio_range(&quadrature_encoder_program, &pio, &sm, &offset, pin, 1, true);

    quadrature_encoder_program_init(pio,sm,offset,pin,max_step_rate);

}

```

Which works for 3 cases ( pins 32/33, 36/37, 39/40) but if I attempt to create the next object (doesn't matter if I set another PIO) it's a hard crash. I'm guessing it's either because I need to instantiate objects differently than I do or there is a hard limit?

My object instance metho:
```


        PioEncoder(const uint pin, PIO pio = pio0, const uint sm = -1, const bool flip = false,
                   const int zero_offset = 0, const uint8_t count_mode = COUNT_4X, const int max_step_rate = 0);
```

I HAVE gotten it to work with checks and setting pio_set_gpio_base(pio, 16); and the like. But it's crash prone.  Perhaps I'm missing something, but the WS led example did not clarify.

**Comment by lurch** [comment] 2026-02-12 18:30
@poetaster It's possible that you're running into the same problem being reported in #2792 ?

**Comment by peterharperuk** [comment] 2026-02-12 18:40
> but if I attempt to create the next object (doesn't matter if I set another PIO) it's a hard crash

You're not giving us a lot to go on. Do you have a call stack? Are you checking "success" is true?

**Comment by poetaster** [comment] 2026-02-12 19:00
> [@poetaster](https://github.com/poetaster) It's possible that you're running into the same problem being reported in [#2792](https://github.com/raspberrypi/pico-sdk/pull/2792) ?

Could well be. More reading.

**Comment by poetaster** [comment] 2026-02-12 19:03
> > but if I attempt to create the next object (doesn't matter if I set another PIO) it's a hard crash
> 
> You're not giving us a lot to go on. Do you have a call stack? Are you checking "success" is true?

success is always true, until you set PIO and base.  If you switch base, you have to switch PIO it seems. But, no can do. I'll try to produce a pure sdk example.

**Comment by peterharperuk** [comment] 2026-02-12 19:15
The gpio base applies to everything on the pio instance. So if you need a different gpio base you have to use a different pio. pio_claim_free_sm_and_add_program_for_gpio_range tries to choose a pio that is compatible with the gpio you are asking for, or else it will choose another one

**Comment by poetaster** [comment] 2026-02-13 06:30
> The gpio base applies to everything on the pio instance. So if you need a different gpio base you have to use a different pio. pio_claim_free_sm_and_add_program_for_gpio_range tries to choose a pio that is compatible with the gpio you are asking for, or else it will choose another one

Yes, I'm aware of that. The point is that in a  program that attempts to use both ranges, I generally get a hung processor. Given my above class, if instantiate and 'begin':
```
PioEncoder encB(39, PIO pio1);
PioEncoder encC(32, PIO, pio1);
PioEncoder encD(36, PIO, pio1);

PioEncoder encA(6, PIO, pio0);
````
followed 
```
pio_set_gpio_base(PIO pio1, 16);
encB.begin();
encC.begin();
encD.begin();
pio_set_gpio_base(PIO pio0, 0);
encA.begin();
````
This succeeds BUT as soon as I call encA, it's a  hard crash 
```
  Serial.print(encA.getCount());
  Serial.print("\t\t");
  
  Serial.print(encB.getCount());
  Serial.print("\t\t");
  
  Serial.print(encC.getCount());
  Serial.print("\t\t");

  Serial.print(encD.getCount());
```

If I don't use encA, the program runs.

EDIT: it's also a hard crash if you try to set PIO pio0 to the 16 base.

**Comment by poetaster** [comment] 2026-02-13 06:35
Which, I know, simply shows that the pio0 was not allocated. Question is, should it? In the above case, it's only 4 sms on 8 pins, 3 in the > 31 range and one below.

**Comment by poetaster** [comment] 2026-02-13 06:50
Ok, I don't know how reliable this is, but it currently runs. Changing the begin method to:

```

void PioEncoder::begin(){
    pinMode(pin, INPUT);
    pinMode(pin+1, INPUT);

    if(pin > 31 && pio_get_gpio_base(pio) != 16) {
        this->pio = PIO pio1;
        pio_set_gpio_base(pio, 16);
    }
    if (!not_first_instance){
        offset = pio_add_program(pio, &quadrature_encoder_program);
    }
    not_first_instance=true;
    if (sm==-1){
        sm = pio_claim_unused_sm(pio, true);
    }
    sm=sm;
    quadrature_encoder_program_init(pio,sm,offset,pin,max_step_rate);

}



PioEncoder encB(39, PIO pio1);
PioEncoder encC(32, PIO pio1);
PioEncoder encD(36, PIO pio1);
PioEncoder encA(6, PIO pio0);

void setup() {
  encB.begin();
  encC.begin();
  encC.flip();
  encD.begin();
  encD.flip();

  pio_set_gpio_base(PIO pio0, 0);
  encA.begin();
  
  Serial.begin(115200);
  while(!Serial);
}

void loop() {
  Serial.print(encA.getCount());
  Serial.print("\t\t"); 
  Serial.print(encB.getCount());
  Serial.print("\t\t"); 
  Serial.print(encC.getCount());
  Serial.print("\t\t");
  Serial.print(encD.getCount());
  Serial.print("\n");
  delay(10);
}


```
AND starting the > 31 objects first I can allocated 2 pios and have the full range. But it feels wrong. But it does work (at the moment!)

**Comment by peterharperuk** [comment] 2026-02-13 11:44
> But it feels wrong

What feels wrong? Is "not_first_instance" a global? If it is, how is pio_add_program called for pio0?

**Comment by poetaster** [comment] 2026-02-13 12:14
> > But it feels wrong
> 
> What feels wrong? Is "not_first_instance" a global? If it is, how is pio_add_program called for pio0?

Sure enough, this method worked a couple of runs and then, not. I'm a bit confounded since it doesn't seem like https://github.com/raspberrypi/pico-sdk/pull/2792  is relavent.

What happens when another object comes along and tries to add a program? In practice, this morning, adding this method to a complex program where I2S uses a pio it appears that the pio_set_gpio_base(PIO pio0, 0); call causes a crash. In any case, it's not the begin() method, per se that bothers me, just the whole hacking it. 

It doesn't work with multiple PIOs and both ranges, but 
```
/bool success = pio_claim_free_sm_and_add_program_for_gpio_range(&quadrature_encoder_program, &pio, &sm, &offset, pin, 1, true);
```
seems like a cleaner method, though one loses a grip on the offsets. In any case, I've kludges it  up for the time being and will just follow what's happening in #2792 to see if that clarifies anything.

**Comment by peterharperuk** [comment] 2026-02-13 12:29
> It doesn't work with multiple PIOs and both ranges, but

I'll test it again, but I don't think you've demonstrated that it doesn't work. What's the crash?

This example did work with multiple PIOs although it's a bit simple https://github.com/raspberrypi/pico-examples/blob/master/pio/pio_blink/blink.c

**Comment by poetaster** [comment] 2026-02-13 13:08
> > It doesn't work with multiple PIOs and both ranges, but
> 
> I'll test it again, but I don't think you've demonstrated that it doesn't work. What's the crash?

I'll try using the blink example since it  does a number of things that I hadn't seen in other examples. 

EDIT: It's a bit apples and oranges.If I understand correctly, SM, OFFSET and obviously PIO need to be tracked separately for lower and upper base, correct? It's a bit messy translating the linear blink example to objects.  Unhappy with the idea of passing around pointers to shared arrays.  I do 'know' that pio_claim_free_sm_and_add_program_for_gpio_range() works for pin > 32 so I'll just kick the can around a bit and see if I can find a solution. For the time being, I'm just using the upper range and polling the one lower (since it's only one and I have cycles).

**Comment by lurch** [comment] 2026-02-14 20:52
> If I understand correctly, SM, OFFSET and obviously PIO need to be tracked separately for lower and upper base, correct?

Each PIO block (there's 2 in RP2040 and 3 in RP2350) has 4 state machines and 32 words of instruction memory. The "offset" records where in the PIO's instruction-memory each PIO-program starts (if you're clever, you can squeeze several different PIO programs into those 32 words). Each state machine in a PIO block can either run a different PIO program, or run the same PIO program. So in the "simple" case where you've only got a single PIO program and multiple state machines running the same program on different pins, I guess you could just force the offset to always be 0.
On RP2040 and RP2350A, there are only 30 GPIO pins, so PIO always addresses the "lower" range. On RP2350B, each PIO can either address the "lower" range (GPIOs 0-31) or the "upper" range (GPIOs 16-47) and this applies to all state machines in that PIO block.

I dunno if it helps, but I've tried to make the `pio_blink` example a bit easier to understand: https://github.com/raspberrypi/pico-examples/pull/737

**Comment by poetaster** [comment] 2026-02-14 21:26
> > If I understand correctly, SM, OFFSET and obviously PIO need to be tracked separately for lower and upper base, correct?
> 
> Each PIO block (there's 2 in RP2040 and 3 in RP2350) has 4 state machines and 32 words of instruction memory. The "offset" records where in the PIO's instruction-memory each PIO-program starts (if you're clever, you can squeeze several different PIO programs into those 32 words). Each state machine in a PIO block can either run a different PIO program, or run the same PIO program. So in the "simple" case where you've only got a single PIO program and multiple state machines running the same program on different pins, I guess you could just force the offset to always be 0. On RP2040 and RP2350A, there are only 30 GPIO pins, so PIO always addresses the "lower" range. On RP2350B, each PIO can either address the "lower" range (GPIOs 0-31) or the "upper" range (GPIOs 16-47) and this applies to all state machines in that PIO block.
> 
> I dunno if it helps, but I've tried to make the `pio_blink` example a bit easier to understand: [raspberrypi/pico-examples#737](https://github.com/raspberrypi/pico-examples/pull/737)

Yeah, I was aware of all this BUT for the 'luxury' problem of the RP2350B, which is the processor I use for 2 projects because of the extra ADC. The problem is that the state has to be managed in a way that requires a number of globals (woll, global to your main). This was so 'easy' before the gpio_base issue. Dynamically making N number of of objects was just:

```void PioEncoder::begin(){
    pinMode(pin, INPUT);
    pinMode(pin+1, INPUT);
    if (!not_first_instance){
        offset = pio_add_program(pio, &quadrature_encoder_program);
    }
    not_first_instance=true;
    if (sm==-1){
        sm = pio_claim_unused_sm(pio, true);
    }
    sm=sm;
    quadrature_encoder_program_init(pio,sm,offset,pin,max_step_rate);
}
```
Here, we had a return of the offset on the initial add, and sm by the pio_claim call. All local to the object. I can't see a way of doing this now without numerous globals? I took a crack at it, but in my context I have:
1. uart pios (midi) 2 pins two sm
2. i2s pios (dac) 2 pins two sm
3. encoder pios 8 pins, 4sm (two ranges).
4. button debouncers (though I removed those for testing)

So, manually managing the sm is not an option, though I could build a custom driver just for a 'one time application'. But I'm trying to re-use code across projects which is beginning to look unlikely.

EDIT: removed example since it's crap. 

In any case, thanks for your efforts, it's easier to parse, the example now. In a way, I might be better off looking at the implementation of  pio_claim_free_sm_and_add_program_for_gpio_range

**Comment by lurch** [comment] 2026-02-14 21:56
I think the only global state you need to keep track of is which PIOs are using the "low range" and which PIOs are using the "high range"? I guess if you want to keep things simple, one approach might be to have a "low-range encoder" which only allows GPIOs 0-31, and a "high-range encoder" which only allows GPIOs 16-47 ?

**Comment by poetaster** [comment] 2026-02-15 09:34
> I think the only global state you need to keep track of is which PIOs are using the "low range" and which PIOs are using the "high range"? I guess if you want to keep things simple, one approach might be to have a "low-range encoder" which only allows GPIOs 0-31, and a "high-range encoder" which only allows GPIOs 16-47 ?

That's what I'm doing now. Made a second object which only works for the higher range. Seems to be stable. Certainly better than a bunch of conditionals everywhere :)
