### ISSUE TITLE
pwm.h compilation error for pico2

### ISSUE THREAD

**Issue by Memotech-Bill** [raspberrypi/pico-sdk#1847] opened 2024-08-19 19:34 UTC
I am obtaining the following compilation error:

````
[ 10%] Building C object CMakeFiles/bbcbasic.dir/pico_stub.c.obj
In file included from /home/pi/pico/PicoBB/console/pico/build/pico_stub.c:1575:
/home/pi/pico/pico-sdk/src/rp2_common/hardware_pwm/include/hardware/pwm.h: In function 'pwm_set_irq_mask_enabled':
/home/pi/pico/pico-sdk/src/rp2_common/hardware_pwm/include/hardware/pwm.h:658:55: error: expected ',' before ')' token
     static_assert(PWM_IRQ_WRAP_1 == PWM_IRQ_WRAP_0 + 1);
                                                       ^
                                                       ,
make[2]: *** [CMakeFiles/bbcbasic.dir/build.make:204: CMakeFiles/bbcbasic.dir/pico_stub.c.obj] Error 1
````

The relevant section of pwm.h is:

````
static inline void pwm_set_irq_mask_enabled(uint32_t slice_mask, bool enabled) {
    valid_params_if(HARDWARE_PWM, slice_mask < 256);
#if PICO_RP2040
    if (enabled) {
        hw_set_bits(&pwm_hw->inte, slice_mask);
    } else {
        hw_clear_bits(&pwm_hw->inte, slice_mask);
    }
#else
    static_assert(PWM_IRQ_WRAP_1 == PWM_IRQ_WRAP_0 + 1);
    uint irq_index = PWM_DEFAULT_IRQ_NUM() - PWM_IRQ_WRAP_0;
    if (enabled) {
        hw_set_bits(&pwm_hw->irq_ctrl[irq_index].inte, slice_mask);
    } else {
        hw_clear_bits(&pwm_hw->irq_ctrl[irq_index].inte, slice_mask);
    }
#endif
}
````

This is compiling on Bullseye. It looks as though the compiler is requiring an error message in `static_assert()`. Apparently this is only optional with C+17 or later.

**Comment by kilograham** [comment] 2024-08-19 19:42
duplicate of #1788 fixed in devleop

**Closed by kilograham** 2024-08-19 19:42 UTC
