### ISSUE TITLE
WIFI connection stability issues

### ISSUE THREAD

**Issue by deival1980** [raspberrypi/pico-sdk#1086] opened 2022-11-01 22:29 UTC
Hello raspberrypi team,

I have here an issue using a mesh router environment, where all the APs are having the same SSID and the connection will be managed by main AP. In this [issue](https://github.com/earlephilhower/arduino-pico/issues/944) in the [arduino-pico repo](https://github.com/earlephilhower/arduino-pico) of [@earlephilhower](https://github.com/earlephilhower) he mentioned, that in your API it is not possible to connect to a specific BSSID as the methods for that are not exposed. Also the methods for getting RSSI and BSSID of the currently connected AP are not exposed.  Can you please check if you could provide official access to that features in your API, and check with Cypress, if they see issues using [AVM FritzBox](https://avm.de/produkte/fritzbox/) 'mesh' WIFI router systems?

Thank you so much in advance!

**Comment by peterharperuk** [comment] 2022-11-23 11:54
Duplicate of https://github.com/raspberrypi/pico-sdk/issues/1090?

> and check with Cypress
I think you'd get an answer from Infineon as quickly as we would.

**Closed** 2023-02-08 16:50 UTC
