### ISSUE TITLE
fatal error: pico/version.h: No such file or directory

### ISSUE THREAD

**Issue by PaulskPt** [raspberrypi/pico-sdk#354] opened 2021-04-23 18:45 UTC
Error in file pico-sdk/src/common/pico_base/include/pico.h: line 17: '"#include "pico/version.h"
is caused by the fact the the name of the file in subfolder: 'pico-sdk/src/common/pico_base/include/pico/' is not 'version.h' but 'version.h.in'.

**Comment by lurch** [comment] 2021-04-23 18:58
This file is actually autogenerated by the build system. See also https://github.com/raspberrypi/pico-feedback/issues/148

**Comment by kilograham** [comment] 2021-04-28 00:06
you don't say what you are doing to get the error, sounds like duplicate of linked issue anyway (which is that you haven't built yet)

**Closed by kilograham** 2021-04-28 00:06 UTC

**Comment by PaulskPt** [comment] 2021-04-28 12:02
Problem solved. Re-installed the pico-sdk; checked installation of other parts of toolchain. Updated pimoroni's libraries for equipment used. Now the toolchain compiles and builds OK.  Thank you.
