### ISSUE TITLE
PPB: missing C API for setting the SysTick, and other exceptions priorities

### ISSUE THREAD

**Issue by DipSwitch** [raspberrypi/pico-sdk#1135] opened 2022-12-06 08:10 UTC
Currently there is no C API for setting the SHRP2 and SHRP3 registers. So now I have to set the priority of the exceptions with something like this:

```
io_rw_32 *p = (io_rw_32 *)((PPB_BASE + M0PLUS_SHPR3_OFFSET));
*p |= ((0xc0) << (M0PLUS_SHPR3_PRI_15_LSB / 8 * 8));
```

**Comment by alastairpatrick** [comment] 2022-12-06 22:21
https://github.com/raspberrypi/pico-sdk/issues/987

**Comment by kilograham** [comment] 2023-05-26 16:02
closing as duplicate of #987

**Closed by kilograham** 2023-05-26 16:02 UTC
