### ISSUE TITLE
Assembler syntax rejected by Clang

### ISSUE THREAD

**Issue by eskimo-software** [raspberrypi/pico-sdk#797] opened 2022-05-01 11:07 UTC
Clang (LLVM 14.0.0) barfs on some of the assembler syntax in SDK files.

- 'rsbs' instruction not accepted, equivalent 'negs' is.
- Some argument syntax isn't accepted (e.g '=(SIO_BASE)' isn't, '=SIO_BASE' is; '=#blah' isn't, '=blah' is.
- 'adr' argument can't be an expression, but can be a .equ that uses an expression.
- Declaration of 'd2fix_a' shouldn't use 'regular_func' macro, because 'd2fix_a' should be a weak symbol.

**Comment by a-gavin** [comment] 2022-05-01 20:58
@eskimo-software This appears to be a duplicate of #789. Suggest closing the other if so?

**Comment by kilograham** [comment] 2022-05-04 21:23
merged into develop

**Closed by kilograham** 2022-05-04 21:23 UTC
